
title: catatan
baseurl: "/catatan"
url: "https://fxah.github.io"
timezone: Asia/Jakarta
owner : Andrea Hifran
epoch : 2015
twitter_username: fxah
github_username:  fxah
permalink: /:year/:month/:day/:title/
paginate: 8
markdown: redcarpet
redcarpet:
    extensions: 
        - tables
        - autolink
        - strikethrough
        - underline
        - highlight
        - lax_spacing
        - superscript
        - space_after_headers
        - with_toc_data
        - footnotes
        - fenced_code_blocks
        - no_intra_emphasis
        - smart
gems:
    - jemoji
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - prepare-label.sh
    - prepare-icons.sh
    - preview-bundle.sh

